// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN-qRzNdH1Hl3lzW7EntSqva9pZPYKrzo',
    appId: '1:1094029279602:web:c0245cad9ba77304aaddeb',
    messagingSenderId: '1094029279602',
    projectId: 'light-controller-11de7',
    authDomain: 'light-controller-11de7.firebaseapp.com',
    databaseURL: 'https://light-controller-11de7-default-rtdb.firebaseio.com',
    storageBucket: 'light-controller-11de7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRnav4EeLyfnsFmUG8uhNaLXkvAf_qdY0',
    appId: '1:1094029279602:android:3f5227300c748c53aaddeb',
    messagingSenderId: '1094029279602',
    projectId: 'light-controller-11de7',
    databaseURL: 'https://light-controller-11de7-default-rtdb.firebaseio.com',
    storageBucket: 'light-controller-11de7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaF16o51mNiJR95Sb4a4yOelpE3KbTDQw',
    appId: '1:1094029279602:ios:c771cbbae66b465caaddeb',
    messagingSenderId: '1094029279602',
    projectId: 'light-controller-11de7',
    databaseURL: 'https://light-controller-11de7-default-rtdb.firebaseio.com',
    storageBucket: 'light-controller-11de7.firebasestorage.app',
    iosBundleId: 'com.example.lightControllerIot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaF16o51mNiJR95Sb4a4yOelpE3KbTDQw',
    appId: '1:1094029279602:ios:c771cbbae66b465caaddeb',
    messagingSenderId: '1094029279602',
    projectId: 'light-controller-11de7',
    databaseURL: 'https://light-controller-11de7-default-rtdb.firebaseio.com',
    storageBucket: 'light-controller-11de7.firebasestorage.app',
    iosBundleId: 'com.example.lightControllerIot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN-qRzNdH1Hl3lzW7EntSqva9pZPYKrzo',
    appId: '1:1094029279602:web:0b929257efc00a8aaaddeb',
    messagingSenderId: '1094029279602',
    projectId: 'light-controller-11de7',
    authDomain: 'light-controller-11de7.firebaseapp.com',
    databaseURL: 'https://light-controller-11de7-default-rtdb.firebaseio.com',
    storageBucket: 'light-controller-11de7.firebasestorage.app',
  );
}
